In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
import re

In [3]:
carpeta = Path("raw")

archivos_csv = list(carpeta.glob("*.csv"))

print("Archivos encontrados:")
for archivo in archivos_csv:
    print(archivo)

dataframes = {}

for archivo in archivos_csv:
    dataframes[archivo.stem] = pd.read_csv(archivo)

print(dataframes.keys())

Archivos encontrados:
raw/spotify_dataset.csv
raw/the_grammy_awards.csv
dict_keys(['spotify_dataset', 'the_grammy_awards'])

In [4]:
# Data first rows to inspect
print(dataframes["spotify_dataset"].head(5))

   Unnamed: 0                track_id                 artists  \
0           0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino
1           1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward
2           2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN
3           3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis
4           4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet

                                          album_name  \
0                                             Comedy
1                                   Ghost (Acoustic)
2                                     To Begin Again
3  Crazy Rich Asians (Original Motion Picture Sou...
4                                            Hold On

                   track_name  popularity  duration_ms  explicit  \
0                      Comedy          73       230666     False
1            Ghost - Acoustic          55       149610     False
2              To Begin Again          57       210826     False
3  Can't Help Falling In Love          71       201933     False
4                     Hold On          82       198853     False

   danceability  energy  ...  loudness  mode  speechiness  acousticness  \
0         0.676  0.4610  ...    -6.746     0       0.1430        0.0322
1         0.420  0.1660  ...   -17.235     1       0.0763        0.9240
2         0.438  0.3590  ...    -9.734     1       0.0557        0.2100
3         0.266  0.0596  ...   -18.515     1       0.0363        0.9050
4         0.618  0.4430  ...    -9.681     1       0.0526        0.4690

   instrumentalness  liveness  valence    tempo  time_signature  track_genre
0          0.000001    0.3580    0.715   87.917               4     acoustic
1          0.000006    0.1010    0.267   77.489               4     acoustic
2          0.000000    0.1170    0.120   76.332               4     acoustic
3          0.000071    0.1320    0.143  181.740               3     acoustic
4          0.000000    0.0829    0.167  119.949               4     acoustic

[5 rows x 21 columns]

In [5]:
print(dataframes["the_grammy_awards"].head(5))

   year                              title               published_at  \
0  2019  62nd Annual GRAMMY Awards  (2019)  2020-05-19T05:10:28-07:00
1  2019  62nd Annual GRAMMY Awards  (2019)  2020-05-19T05:10:28-07:00
2  2019  62nd Annual GRAMMY Awards  (2019)  2020-05-19T05:10:28-07:00
3  2019  62nd Annual GRAMMY Awards  (2019)  2020-05-19T05:10:28-07:00
4  2019  62nd Annual GRAMMY Awards  (2019)  2020-05-19T05:10:28-07:00

                  updated_at            category     nominee         artist  \
0  2020-05-19T05:10:28-07:00  Record Of The Year     Bad Guy  Billie Eilish
1  2020-05-19T05:10:28-07:00  Record Of The Year     Hey, Ma       Bon Iver
2  2020-05-19T05:10:28-07:00  Record Of The Year     7 rings  Ariana Grande
3  2020-05-19T05:10:28-07:00  Record Of The Year  Hard Place         H.E.R.
4  2020-05-19T05:10:28-07:00  Record Of The Year        Talk         Khalid

                                             workers  \
0  Finneas O'Connell, producer; Rob Kinelski & Fi...
1  BJ Burton, Brad Cook, Chris Messina & Justin V...
2  Charles Anderson, Tommy Brown, Michael Foster ...
3  Rodney “Darkchild” Jerkins, producer; Joseph H...
4  Disclosure & Denis Kosiak, producers; Ingmar C...

                                                 img  winner
0  https://www.grammy.com/sites/com/files/styles/...    True
1  https://www.grammy.com/sites/com/files/styles/...    True
2  https://www.grammy.com/sites/com/files/styles/...    True
3  https://www.grammy.com/sites/com/files/styles/...    True
4  https://www.grammy.com/sites/com/files/styles/...    True

In [6]:
# Data shape or dimensions
print("Shape or df dimensions spotify_dataset:", dataframes["spotify_dataset"].shape)
print("\nColumns spotify_dataset:")
print(dataframes["spotify_dataset"].columns.tolist())
print("----------------------------------------------------------------------------------------------------------------------------------------------")
print(" ")
print("Shape or df dimensions the_grammy_awards:", dataframes["the_grammy_awards"].shape)
print("\nColumns the_grammy_awards:")
print(dataframes["the_grammy_awards"].columns.tolist())

Shape or df dimensions spotify_dataset: (114000, 21)

Columns spotify_dataset:
['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name', 'popularity', 'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature', 'track_genre']
----------------------------------------------------------------------------------------------------------------------------------------------

Shape or df dimensions the_grammy_awards: (4810, 10)

Columns the_grammy_awards:
['year', 'title', 'published_at', 'updated_at', 'category', 'nominee', 'artist', 'workers', 'img', 'winner']

In [7]:
# Data types
print("Data types spotify_dataset:", dataframes["spotify_dataset"].dtypes)

Data types spotify_dataset: Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [8]:
print("Data types the_grammy_awards:", dataframes["the_grammy_awards"].dtypes)

Data types the_grammy_awards: year             int64
title           object
published_at    object
updated_at      object
category        object
nominee         object
artist          object
workers         object
img             object
winner            bool
dtype: object

In [9]:
# Missing values spotify_dataset
print("Missing values:")
print(dataframes["spotify_dataset"].isnull().sum())

Missing values:
Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [10]:
# % Missing values spotify_dataset
print("%Missing values:")
print((dataframes["spotify_dataset"].isnull().sum() / len(dataframes["spotify_dataset"]) * 100).round(4))

%Missing values:
Unnamed: 0          0.0000
track_id            0.0000
artists             0.0009
album_name          0.0009
track_name          0.0009
popularity          0.0000
duration_ms         0.0000
explicit            0.0000
danceability        0.0000
energy              0.0000
key                 0.0000
loudness            0.0000
mode                0.0000
speechiness         0.0000
acousticness        0.0000
instrumentalness    0.0000
liveness            0.0000
valence             0.0000
tempo               0.0000
time_signature      0.0000
track_genre         0.0000
dtype: float64

In [11]:
# Missing values the_grammy_awards
print("Missing values:")
print(dataframes["the_grammy_awards"].isnull().sum())

Missing values:
year               0
title              0
published_at       0
updated_at         0
category           0
nominee            6
artist          1840
workers         2190
img             1367
winner             0
dtype: int64

In [12]:
# % Missing values the_grammy_awards
print("%Missing values:")
print((dataframes["the_grammy_awards"].isnull().sum() / len(dataframes["the_grammy_awards"]) * 100).round(2))

%Missing values:
year             0.00
title            0.00
published_at     0.00
updated_at       0.00
category         0.00
nominee          0.12
artist          38.25
workers         45.53
img             28.42
winner           0.00
dtype: float64

In [13]:
# Cardinality od categorical columns in spotify_dataset
# Check cardinality of categorical columns
print("\nCardinality of categorical columns:")
    
df = dataframes["spotify_dataset"]

categorical_cols = df.select_dtypes(include=["object", "category"]).columns

print("Categorical columns found:")
print(list(categorical_cols))

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique(dropna=False))
    print("Top values:")
    print(df[col].value_counts(dropna=False).head())

Cardinality of categorical columns:
Categorical columns found:
['track_id', 'artists', 'album_name', 'track_name', 'track_genre']

--- track_id ---
Unique values: 89741
Top values:
track_id
6S3JlDAGk3uu3NtZbPnuhS    9
2Ey6v4Sekh3Z0RUSISRosD    8
2kkvB3RNRzwjFdGhaUA0tz    8
5ZsAhuQ24mWHiduaxJqnhW    7
08kTa3SL9sV6Iy8KLKtGql    7
Name: count, dtype: int64

--- artists ---
Unique values: 31438
Top values:
artists
The Beatles        279
George Jones       271
Stevie Wonder      236
Linkin Park        224
Ella Fitzgerald    222
Name: count, dtype: int64

--- album_name ---
Unique values: 46590
Top values:
album_name
Alternative Christmas 2022     195
Feliz Cumpleaños con Perreo    184
Metal                          143
Halloween con perreito         123
Halloween Party 2022           115
Name: count, dtype: int64

--- track_name ---
Unique values: 73609
Top values:
track_name
Run Rudolph Run                   151
Halloween                          88
Frosty The Snowman                 81
Little Saint Nick - 1991 Remix     76
Last Last                          75
Name: count, dtype: int64

--- track_genre ---
Unique values: 114
Top values:
track_genre
acoustic             1000
punk-rock            1000
progressive-house    1000
power-pop            1000
pop                  1000
Name: count, dtype: int64

In [14]:
# Cardinality od categorical columns
# Check cardinality of categorical columns
print("\nCardinality of categorical columns:")
    
df = dataframes["the_grammy_awards"]

categorical_cols = df.select_dtypes(include=["object", "category", "bool"]).columns

print("Categorical columns found:")
print(list(categorical_cols))

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique(dropna=False))
    print("Top values:")
    print(df[col].value_counts(dropna=False).head())

Cardinality of categorical columns:
Categorical columns found:
['title', 'published_at', 'updated_at', 'category', 'nominee', 'artist', 'workers', 'img', 'winner']

--- title ---
Unique values: 62
Top values:
title
62nd Annual GRAMMY Awards  (2019)    433
50th Annual GRAMMY Awards  (2007)    111
51st Annual GRAMMY Awards  (2008)    111
49th Annual GRAMMY Awards  (2006)    110
53rd Annual GRAMMY Awards  (2010)    109
Name: count, dtype: int64

--- published_at ---
Unique values: 4
Top values:
published_at
2017-11-28T00:03:45-08:00    4205
2020-05-19T05:10:28-07:00     433
2018-12-06T23:48:49-08:00      86
2018-05-22T03:08:24-07:00      86
Name: count, dtype: int64

--- updated_at ---
Unique values: 10
Top values:
updated_at
2019-09-10T01:08:19-07:00    778
2019-09-10T01:06:11-07:00    754
2019-09-10T01:07:37-07:00    713
2019-09-10T01:06:59-07:00    681
2019-09-10T01:11:09-07:00    658
Name: count, dtype: int64

--- category ---
Unique values: 638
Top values:
category
Song Of The Year        70
Record Of The Year      69
Album Of The Year       66
Best Opera Recording    64
Best Album Notes        63
Name: count, dtype: int64

--- nominee ---
Unique values: 4132
Top values:
nominee
Bridge Over Troubled Water    7
Robert Woods                  7
Berlioz: Requiem              7
Steven Epstein                7
NaN                           6
Name: count, dtype: int64

--- artist ---
Unique values: 1659
Top values:
artist
NaN                  1840
(Various Artists)      66
U2                     18
Aretha Franklin        16
Ella Fitzgerald        13
Name: count, dtype: int64

--- workers ---
Unique values: 2367
Top values:
workers
NaN                                        2190
John Williams, composer (John Williams)      20
Vladimir Horowitz, artist                    15
Henry Mancini, arranger (Henry Mancini)       8
(Chicago Symphony Orchestra)                  7
Name: count, dtype: int64

--- img ---
Unique values: 1464
Top values:
img
NaN                                                                                                                                                      1367
https://www.grammy.com/sites/com/files/styles/artist_circle/public/muzooka/John%2BWilliams/John%2520Williams_1_1_1597170495.jpg?itok=GsnrkP98              26
https://www.grammy.com/sites/com/files/styles/artist_circle/public/muzooka/U2/U2_1_1_1578385236.jpg?itok=rQVhxxhL                                          22
https://www.grammy.com/sites/com/files/styles/artist_circle/public/muzooka/Vladimir%2BHorowitz/Vladimir%2520Horowitz_1_1_1597176026.jpg?itok=QiT9d29e      21
https://www.grammy.com/sites/com/files/styles/artist_circle/public/muzooka/Henry%2BMancini/Henry%2520Mancini_1_1_1581553583.jpg?itok=oMIyl-mj              20
Name: count, dtype: int64

--- winner ---
Unique values: 1
Top values:
winner
True    4810
Name: count, dtype: int64

In [15]:
# Basic Statistics spotify_dataset 
print("Describe data:")
dataframes["spotify_dataset"].describe()

Describe data:

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [16]:
# Basic Statistics the_grammy_awards
print("Describe data:")
dataframes["the_grammy_awards"].describe()

Describe data:

              year
count  4810.000000
mean   1995.566944
std      17.149720
min    1958.000000
25%    1983.000000
50%    1998.000000
75%    2010.000000
max    2019.000000

In [17]:
#counting rows that are repeated in their entirety
df = dataframes["spotify_dataset"]
print(df.duplicated().sum())

0

In [18]:
#number of duplicates for track_id
dataframes["spotify_dataset"]["track_id"].duplicated().sum()

np.int64(24259)

In [19]:
#number of times the track_id is repeated
vc = dataframes["spotify_dataset"]["track_id"].value_counts()
vc[vc > 1]

track_id
6S3JlDAGk3uu3NtZbPnuhS    9
2Ey6v4Sekh3Z0RUSISRosD    8
2kkvB3RNRzwjFdGhaUA0tz    8
5ZsAhuQ24mWHiduaxJqnhW    7
08kTa3SL9sV6Iy8KLKtGql    7
                         ..
2a05MFdR1vtm8QVKFs1SGn    2
2BJdsyqP0IfOt0GR2a6zJl    2
7oyFihJppZYPP7o0NfoHnZ    2
0oz7Ia8lnWttkXi2TBc1Rd    2
1cbCEtcGU25HvwMrZDPqJy    2
Name: count, Length: 16641, dtype: int64

In [20]:
# Value counts o duplicated data 
# Invoice id or unique identifier for each transaction 
dataframes["spotify_dataset"]["artists"].value_counts()

artists
The Beatles                                                                 279
George Jones                                                                271
Stevie Wonder                                                               236
Linkin Park                                                                 224
Ella Fitzgerald                                                             222
                                                                           ...
Automatic Tasty                                                               1
o9                                                                            1
Pyotr Ilyich Tchaikovsky;National Philharmonic Orchestra;Richard Bonynge      1
tstewart;Ólafur Arnalds                                                       1
Jesus Culture                                                                 1
Name: count, Length: 31437, dtype: int64

In [21]:
df = dataframes["spotify_dataset"].copy()

artistas_df = df[["artists"]].dropna().copy()

artistas_df["artists_normalizado"] = (
    artistas_df["artists"]
    .str.strip()
    .str.lower()
)

variantes_artistas = (
    artistas_df.groupby("artists_normalizado")["artists"]
    .agg(["nunique", lambda x: list(x.unique())])
    .reset_index()
)

variantes_artistas.columns = ["artists_normalizado", "formas_distintas", "variantes"]
variantes_artistas = variantes_artistas[variantes_artistas["formas_distintas"] > 1]

display(variantes_artistas)

,artists_normalizado,formas_distintas,variantes
6743,deadlife,2,"[Deadlife, DEADLIFE]"
7056,desejo de menina,2,"[Desejo De Menina, Desejo de Menina]"
7493,dj fixx;ondamike,2,"[DJ Fixx;Ondamike, DJ Fixx;OnDaMiKe]"
9657,fisher,2,"[Fisher, FISHER]"
16311,lisa,2,"[LiSA, LISA]"
16593,los hermanos,2,"[Los Hermanos, LOS HERMANOS]"
22799,ralphi rosario;donna blakely;lego,2,"[Ralphi Rosario;Donna Blakely;Lego, Ralphi Ros..."
25216,shine,2,"[Shine, ShinE]"
27142,terra,2,"[Terra , TERRA]"

In [22]:
# Value counts o duplicated data 
# Invoice id or unique identifier for each transaction 
dataframes["spotify_dataset"]["album_name"].value_counts()

album_name
Alternative Christmas 2022     195
Feliz Cumpleaños con Perreo    184
Metal                          143
Halloween con perreito         123
Halloween Party 2022           115
                              ...
Me Alcançou                      1
Comunhão e Adoração              1
Força Pra Encarar                1
The Way of the Fist              1
Revelation Songs                 1
Name: count, Length: 46589, dtype: int64

In [23]:
df = dataframes["spotify_dataset"].copy()

album_name_df = df[["album_name"]].dropna().copy()

album_name_df["album_name_normalizado"] = (
    album_name_df["album_name"]
    .str.strip()
    .str.lower()
)

variantes_album_name = (
    album_name_df.groupby("album_name_normalizado")["album_name"]
    .agg(["nunique", lambda x: list(x.unique())])
    .reset_index()
)

variantes_album_name.columns = ["album_name_normalizado", "formas_distintas", "variantes"]
variantes_album_name = variantes_album_name[variantes_album_name["formas_distintas"] > 1]

display(variantes_album_name)

,album_name_normalizado,formas_distintas,variantes
180,10 de colección,2,"[10 de Colección, 10 De Colección]"
853,4am,2,"[4am, 4AM]"
1120,a day in the life,2,"[A Day in the Life, A Day In The Life]"
1571,about time,2,"[About Time, about time]"
1694,acústico (ao vivo),2,"[Acústico (Ao Vivo), Acústico (Ao vivo)]"
...,...,...,...
43613,you all look the same to me,2,"[You All Look The Same To Me, You All Look the..."
43632,you broke me first,2,"[You Broke Me First, you broke me first]"
43769,your love,2,"[Your Love, your love]"
43800,youth,2,"[youth, Youth]"
43887,zero,3,"[Zero, zero, ZERO]"

In [24]:
# Value counts o duplicated data 
# Invoice id or unique identifier for each transaction 
dataframes["spotify_dataset"]["track_name"].value_counts()

track_name
Run Rudolph Run                      151
Halloween                             88
Frosty The Snowman                    81
Little Saint Nick - 1991 Remix        76
Last Last                             75
                                    ...
Mitt Gullbergs kaj paradis (Live)      1
Vill Inte Längre                       1
Så länge du är med mig                 1
Just Plain Bad                         1
Barbincor                              1
Name: count, Length: 73608, dtype: int64

In [25]:
df = dataframes["spotify_dataset"].copy()

track_name_df = df[["track_name"]].dropna().copy()

track_name_df["track_name_normalizado"] = (
    track_name_df["track_name"]
    .str.strip()
    .str.lower()
)

variantes_track_name = (
    track_name_df.groupby("track_name_normalizado")["track_name"]
    .agg(["nunique", lambda x: list(x.unique())])
    .reset_index()
)

variantes_track_name.columns = ["track_name_normalizado", "formas_distintas", "variantes"]
variantes_track_name = variantes_track_name[variantes_track_name["formas_distintas"] > 1]

display(variantes_track_name)

,track_name_normalizado,formas_distintas,variantes
2,"""c"" is for cookie",2,"[""C"" IS FOR COOKIE, ""C"" is for Cookie]"
129,(you're the) devil in disguise,2,"[(You're The) Devil in Disguise, (You're The) ..."
564,2am,2,"[2am, 2AM]"
628,3:00 am,2,"[3:00 AM, 3:00 Am]"
662,40 graus de amor - ao vivo,2,"[40 Graus De Amor - Ao Vivo, 40 Graus de Amor ..."
...,...,...,...
68982,мы только знакомы,2,"[Мы Только Знакомы, Мы только знакомы]"
68996,надежда,2,"[надежда, Надежда]"
69057,очи черные,2,"[Очи черные, Очи Черные]"
69118,приходите в мой дом,2,"[Приходите В Мой Дом, Приходите в мой дом]"
69188,средь шумного бала,2,"[Средь шумного бала, Средь Шумного Бала]"

In [26]:
# Value counts o duplicated data 
# Invoice id or unique identifier for each transaction 
dataframes["spotify_dataset"]["track_genre"].value_counts()

track_genre
acoustic             1000
punk-rock            1000
progressive-house    1000
power-pop            1000
pop                  1000
                     ...
folk                 1000
emo                  1000
electronic           1000
electro              1000
world-music          1000
Name: count, Length: 114, dtype: int64

In [27]:
df = dataframes["spotify_dataset"].copy()

track_genre_df = df[["track_genre"]].dropna().copy()

track_genre_df["track_genre_normalizado"] = (
    track_genre_df["track_genre"]
    .str.strip()
    .str.lower()
)

variantes_track_genre = (
    track_genre_df.groupby("track_genre_normalizado")["track_genre"]
    .agg(["nunique", lambda x: list(x.unique())])
    .reset_index()
)

variantes_track_genre.columns = ["track_genre_normalizado", "formas_distintas", "variantes"]
variantes_track_genre = variantes_track_genre[variantes_track_genre["formas_distintas"] > 1]

display(variantes_track_genre)

Empty DataFrame
Columns: [track_genre_normalizado, formas_distintas, variantes]
Index: []